### ISSUE TITLE
background generates regions outside chrom size?

### ISSUE THREAD

**Issue by simonvh** [simonvh/gimmemotifs#15]
simon@mb06 ~/tmp $ gimme motifs -n test -a small -t MDmodule /home/matteo/STEM/p300/fluff/ext_250/gimme/p300_refpeaks_sort_merged_ext_250_no_overscaffold_no_TSS_1kb_50p_130u_norm_prof_corr0.8_reformatted_prof_0.bed -g xenTro3beta 
Output directory test already exists!
Resuming a previous run is not yet implemented. Please specify a different name,
or delete this directory if you really want to overwrite it
2014-07-09 15:23:39,127 - INFO - Logging started
2014-07-09 15:23:39,128 - INFO - Created logfile test/gimme_motifs.log
2014-07-09 15:23:39,129 - INFO - gimme_motifs version 0.8.3
2014-07-09 15:23:39,130 - INFO - Created output directory test (all output files will be stored here)
2014-07-09 15:23:39,133 - INFO - Starting full motif analysis
2014-07-09 15:23:39,147 - INFO - Using temporary directory /tmp/gimmemotifs.12161.unHncT
2014-07-09 15:23:39,154 - INFO - Using pp
2014-07-09 15:23:39,155 - INFO - Parameters:
2014-07-09 15:23:39,156 - INFO -   ncpus: 12
2014-07-09 15:23:39,157 - INFO -   torque: False
2014-07-09 15:23:39,157 - INFO -   lwidth: 500
2014-07-09 15:23:39,158 - INFO -   tools: MDmodule
2014-07-09 15:23:39,159 - INFO -   user_background: None
2014-07-09 15:23:39,159 - INFO -   use_strand: False
2014-07-09 15:23:39,160 - INFO -   scan_cutoff: 0.9
2014-07-09 15:23:39,161 - INFO -   width: 200
2014-07-09 15:23:39,162 - INFO -   genome: xenTro3beta
2014-07-09 15:23:39,162 - INFO -   fraction: 0.2
2014-07-09 15:23:39,163 - INFO -   background: genomic_matched,random
2014-07-09 15:23:39,164 - INFO -   abs_max: 1000
2014-07-09 15:23:39,164 - INFO -   available_tools: MDmodule,MEME,MEMEW,GADEM,MotifSampler,trawler,Improbizer,BioProspector,Posmo,ChIPMunk,JASPAR,AMD,HMS
2014-07-09 15:23:39,165 - INFO -   analysis: small
2014-07-09 15:23:39,166 - INFO -   enrichment: 1.5
2014-07-09 15:23:39,167 - INFO -   keep_intermediate: False
2014-07-09 15:23:39,167 - INFO -   max_time: None
2014-07-09 15:23:39,168 - INFO -   cluster_threshold: 0.95
2014-07-09 15:23:39,169 - INFO -   motif_db: vertebrate_motifs.pwm
2014-07-09 15:23:39,169 - INFO -   pvalue: 0.001
2014-07-09 15:23:39,170 - INFO -   markov_model: 1
2014-07-09 15:23:39,259 - INFO - Could not parse max_time value, setting to no limit
2014-07-09 15:23:39,260 - INFO - Invalid time limit for motif prediction, setting to no limit
2014-07-09 15:23:39,261 - INFO - Preparing input (BED)
2014-07-09 15:24:03,577 - INFO - Creating matched genomic background (xenTro3beta, using genes in /usr/share/gimmemotifs/genes/xenTro3beta.bed)
Traceback (most recent call last):
  File "/usr/bin/gimme", line 400, in <module>
    args.func(args)
  File "/usr/lib64/python2.7/site-packages/gimmemotifs/commands/motifs.py", line 69, in motifs
    gm.run_full_analysis(args.inputfile, params)
  File "/usr/lib64/python2.7/site-packages/gimmemotifs/core.py", line 785, in run_full_analysis
    self.create_background(background, params["genome"], params["width"])
  File "/usr/lib64/python2.7/site-packages/gimmemotifs/core.py", line 399, in create_background
    self._create_background("genomic_matched", self.validation_bed, None, self.prediction_bg, organism=organism, width=width)
  File "/usr/lib64/python2.7/site-packages/gimmemotifs/core.py", line 324, in _create_background
    f = MatchedGenomicFasta(bedfile, gene_file, index_dir, width, nr_times)
  File "/usr/lib64/python2.7/site-packages/gimmemotifs/background.py", line 367, in __init__
    track2fasta(index, tmpbed, tmpfasta)
  File "/usr/lib64/python2.7/site-packages/gimmemotifs/genome_index.py", line 399, in track2fasta
    all_seqs = g.get_sequences(chrom, coords)
  File "/usr/lib64/python2.7/site-packages/gimmemotifs/genome_index.py", line 262, in get_sequences
    raise ValueError, "%s: %s, invalid start, greater than sequence length!" % (chr,start)
ValueError: scaffold_84: 31303539, invalid start, greater than sequence length!

**Comment by simonvh** [comment]
matched_genomic background is removed 52b8b92
