### ISSUE TITLE
gimme background matched_genomic with -f BED fails

### ISSUE THREAD

**Issue by simonvh** [simonvh/gimmemotifs#18]
kprange@mb06 ~/MLL_Fusion/analyses_nov_2014/BRE_motifs $ gimme background -i test.bed -f BED -g hg19 test matched_genomic
Traceback (most recent call last):
  File "/usr/bin/gimme", line 417, in <module>
    args.func(args)
  File "/usr/lib64/python2.7/site-packages/gimmemotifs/commands/background.py", line 71, in background
    bg.create_matched_genomic_bedfile(out, inputfile, gene_file, l, args.number, True)
TypeError: create_matched_genomic_bedfile() takes exactly 7 arguments (6 given)

Test.bed:
kprange@mb06 ~/MLL_Fusion/analyses_nov_2014/BRE_motifs $ cat test.bed
chr1    10011   10053   D256N5M1:154:C55L9ACXX:4:2304:2839:53613        0       -
chr1    10048   10090   D256N5M1:154:C55L9ACXX:4:1111:17209:91625       0       +
chr1    10119   10161   D256N5M1:154:C55L9ACXX:4:2208:9041:60563        0       -
chr1    10127   10169   D256N5M1:154:C55L9ACXX:4:2105:15109:63619       0       +
chr1    10174   10216   D256N5M1:154:C55L9ACXX:4:1315:20800:58785       0       +
chr1    10198   10240   D256N5M1:154:C55L9ACXX:4:1105:5332:10721        0       +
chr1    10234   10276   D256N5M1:154:C55L9ACXX:4:2304:10743:58755       25      +
chr1    10262   10304   D256N5M1:154:C55L9ACXX:4:2205:17772:54808       0       +
chr1    10308   10350   D256N5M1:154:C55L9ACXX:4:1105:2621:91731        23      +
chr1    10354   10396   D256N5M1:154:C55L9ACXX:4:2314:11599:48130       0       +

**Comment by simonvh** [comment]
matched_genomic is removed 52b8b92
