### ISSUE TITLE
Error when running Quick GimmeMotifs example [Key Error: 'ncpus'] in mp.py

### ISSUE THREAD

**Issue by devNull2013** [simonvh/gimmemotifs#34]
Hi,
I'm running a debian jessie (8.4) and just installed GimmeMotifs via pip in a virtualenv:
```
cd /home/george
virtualenv GimmeMotifs_pythonEnv
GimmeMotifs_pythonEnv/bin/pip install numpy # 1.11.0
GimmeMotifs_pythonEnv/bin/pip install scipy # 0.17.1
GimmeMotifs_pythonEnv/bin/pip install matplotlib # 1.5.1
GimmeMotifs_pythonEnv/bin/pip install kid # 0.9.6
GimmeMotifs_pythonEnv/bin/pip install pybedtools # 0.7.7
GimmeMotifs_pythonEnv/bin/pip install pandas # 0.18.1
GimmeMotifs_pythonEnv/bin/pip install gimmemotifs # 0.9.0.3

source /home/george/GimmeMotifs_pythonEnv/bin/activate

gimme motifs /home/george/GimmeMotifs_pythonEnv/share/gimmemotifs/examples/TAp73alpha.fa -n /home/george/gimmemotifs_test/p73
```

This results in an error:
```
Traceback (most recent call last):
  File "/home/george/GimmeMotifs_pythonEnv/bin/gimme", line 11, in <module>
    from  gimmemotifs import commands
  File "/home/george/GimmeMotifs_pythonEnv/local/lib/python2.7/site-packages/gimmemotifs/commands/__init__.py", line 8, in <module>
    m =  __import__("{0}.{1}".format(__name__, cmdname), globals(), locals(), [cmdname], -1)
  File "/home/george/GimmeMotifs_pythonEnv/local/lib/python2.7/site-packages/gimmemotifs/commands/cluster.py", line 11, in <module>
    from gimmemotifs.comparison import MotifComparer
  File "/home/george/GimmeMotifs_pythonEnv/local/lib/python2.7/site-packages/gimmemotifs/comparison.py", line 419, in <module>
    from gimmemotifs.mp import pool
  File "/home/george/GimmeMotifs_pythonEnv/local/lib/python2.7/site-packages/gimmemotifs/mp.py", line 5, in <module>
    n_cpus = int(MotifConfig().get_default_params()["ncpus"])
KeyError: 'ncpus'
```
Inspecting the content of `MotifConfig().get_default_params()` it seems like the `ncpus` is indeed not available:
```
>>> MotifConfig().get_default_params()
{'fraction': '0.2', 'use_strand': 'False', 'available_tools': 'MDmodule,MEME,GADEM,MotifSampler,trawler,Improbizer,BioProspector,Posmo,ChIPMunk,JASPAR,AMD,HMS,Homer', 'abs_max': '1000', 'analysis': 'medium', 'pvalue': '0.001', 'width': '200', 'lwidth': '500', 'scan_cutoff': '0.9', 'background': 'genomic_matched,random', 'cluster_threshold': '0.95', 'max_time': 'None', 'motif_db': 'vertebrate_motifs.pwm', 'tools': 'MDmodule,MEME,MotifSampler,trawler,Improbizer,BioProspector,Posmo,ChIPMunk,JASPAR,AMD,HMS,Homer', 'enrichment': '1.5', 'markov_model': '1', 'genome': 'hg19'}
```
A `which ncpus` yields `/usr/bin/ncpus` and results in `8`.

What do you think about this?

Many thanks for your assistance and help.
Regards

**Comment by devNull2013** [comment]
Ok, just noticed that `ncpus` parameter needs to be added to `gimmemotifs.cfg`, ok no problem.
Running the Quick Example with the same command as described above, a different error occurs:
```
Invalid value for background argument
```

Sorry for nagging...

**Comment by simonvh** [comment]
It seems that the default config file is wrong in some places.

You can change the background argument at the command line with -b
gc,random and in the gimmemotifs.cfg under [params] to " background =
gc,random"

Hope this fixes it and sorry for these issues. I'll fix it in a next
release.

**Comment by devNull2013** [comment]
Dear Simon,

many thanks for your quick reply. Now it works perfectly.

Regards
Christian
