### ISSUE TITLE
failed to download genome

### ISSUE THREAD

**Issue by c-guzman** [simonvh/gimmemotifs#54]
Having trouble downloading hg18 genome using `gimme genome . hg18`

```
Retrieving gene annotation for hg18
Using http://hgdownload.cse.ucsc.edu/goldenPath/hg18/database/knownGene.txt.gz
zcat /tmp/tmpKPJNfT.gz | cut -f1-11 | /home/carlos/anaconda2/bin/genePredToBed /dev/stdin /home/carlos/anaconda2/share/gimmemotifs/genes/hg18.bed
Downloading hg18 genome
Trying to download http://hgdownload.soe.ucsc.edu/goldenPath/hg18/bigZips/chromFa.tar.gz
Trying to download http://hgdownload.soe.ucsc.edu/goldenPath/hg18/bigZips/hg18.fa.gz
Failed to download genome
```

The version is 0.10.0.

Using version 0.11.0

```
/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/matplotlib/font_manager.py:280: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '
Retrieving gene annotation for hg18
Using http://hgdownload.cse.ucsc.edu/goldenPath/hg18/database/knownGene.txt.gz
zcat /tmp/tmpn1pj049r.gz | cut -f1-11 | /home/carlos/anaconda2/envs/gimme/bin/genePredToBed /dev/stdin /home/carlos/anaconda2/envs/gimme/share/gimmemotifs/genes/hg18.bed
Downloading hg18 genome
Trying to download http://hgdownload.soe.ucsc.edu/goldenPath/hg18/bigZips/chromFa.tar.gz
Traceback (most recent call last):
  File "/home/carlos/anaconda2/envs/gimme/bin/gimme", line 496, in <module>
    args.func(args)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/genome.py", line 23, in genome
    get_genome(args.genomebuild, args.fastadir, args.indexdir)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/genome_index.py", line 222, in get_genome
    download_genome(genomebuild, genome_dir)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/genome_index.py", line 168, in download_genome
    genome_fa
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by simonvh** [comment]
Thanks for the notice. The naming of UCSC bigZip files is even more inconsistent then I thought. Should be fixed now in the development branch. You can download and install with:
 
```
$ pip install git+https://github.com/simonvh/gimmemotifs.git@develop
```

**Comment by c-guzman** [comment]
This solved the problem. Thanks!
