### ISSUE TITLE
ValueError: Function <function Styler._bar_left at 0x7f4cdc455ae8> returned the wrong shape.

### ISSUE THREAD

**Issue by c-guzman** [simonvh/gimmemotifs#56]
```
reading mapping
Traceback (most recent call last):
  File "/home/carlos/anaconda2/envs/gimme/bin/gimme", line 496, in <module>
    args.func(args)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/roc.py", line 143, in roc
    0.01,
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/roc.py", line 71, in html_report
    f.write(df.sort_values("ROC AUC", ascending=False).style.bar(bar_cols).set_precision(3).set_table_attributes("data-sortable").render().replace("data-sortable", 'class="sortable-theme-slick" data-sortable'))
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/pandas/io/formats/style.py", line 434, in render
    self._compute()
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/pandas/io/formats/style.py", line 502, in _compute
    r = func(self)(*args, **kwargs)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/pandas/io/formats/style.py", line 531, in _apply
    raise ValueError(msg)
ValueError: Function <function Styler._bar_left at 0x7f4cdc455ae8> returned the wrong shape.
Result has shape: (6,)
Expected shape:   (0, 6)
```

Used gimme background with gc to create background regions, no errors.

Used gimme roc, received this error. Tried working on a small number of sequences (39).

**Comment by simonvh** [comment]
This is an error that I can not easily place. Would you mind sharing the sequence set and the background set with me so I can debug locally? And can you send me the output of `conda info` and `conda list`?

**Comment by c-guzman** [comment]
Here are the two files. Had to rename them to .txt, but they are FA files.

[hg18_Chr21_FirstTier_20bp.txt](https://github.com/simonvh/gimmemotifs/files/1246893/hg18_Chr21_FirstTier_20bp.txt)
[random.background.txt](https://github.com/simonvh/gimmemotifs/files/1246894/random.background.txt)

**Comment by simonvh** [comment]
Thanks for that. There were no enriched motifs found and this generated an error while generating the html report. I will fix this bug. You can open the file `gimme.roc.report.txt`, which contains the results in text format. Even though no motifs were found significant, you might want to look at that.
