### ISSUE TITLE
No section params

### ISSUE THREAD

**Issue by c-guzman** [simonvh/gimmemotifs#57]
Tried installing gimmeMotifs on a new ubuntu 16.04 system. Followed installation instructions as shown in the github.

Received this error when trying to run `gimme genome`:

```
gimme genome . hg38
```

```
Traceback (most recent call last):
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/carlos/anaconda2/envs/gimme/bin/gimme", line 11, in <module>
    from  gimmemotifs import commands
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/__init__.py", line 14, in <module>
    m =  __import__("{0}.{1}".format(__name__, cmdname), globals(), locals(), [cmdname], level)
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/location.py", line 14, in <module>
    from gimmemotifs.mp import pool
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/mp.py", line 5, in <module>
    n_cpus = int(MotifConfig().get_default_params()["ncpus"])
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/site-packages/gimmemotifs/config.py", line 66, in get_default_params
    d = dict(self.config.items("params"))
  File "/home/carlos/anaconda2/envs/gimme/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'params'
```

**Comment by simonvh** [comment]
How exactly did you install GimmeMotifs? Conda, pip or source?

**Comment by c-guzman** [comment]
I installed using what you recommend in your README:

```
# Create an environment called gimme with all dependencies
$ conda create -n gimme python=3 pip future numpy scipy matplotlib=2 \
statsmodels scikit-learn seaborn jinja2 bedtools pybedtools \
ucsc-genepredtobed lightning xgboost r-robustrankaggreg pillow pyyaml \
diskcache six ucsc-bigbedtobed xdg xxhash readline ghostscript homer \
gadem trawler weeder xxmotif

# Activate the environment
$ source activate gimme

# Install gimmemotifs
$ pip install https://github.com/simonvh/gimmemotifs/releases/download/0.11.1/gimmemotifs-0.11.1.tar.gz
```

**Comment by simonvh** [comment]
Can you show me the contents of `home/carlos/anaconda2/envs/gimme/share/gimmemotifs/gimmemotifs/cfg`?

**Comment by c-guzman** [comment]
```
[main]
index_dir = /tmp/pip-r1dvzseq-build/build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/genome_index
bg = /tmp/pip-r1dvzseq-build/build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/bg
template_dir = /tmp/pip-r1dvzseq-build/build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/templates
score_dir = /tmp/pip-r1dvzseq-build/build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/score_dists
gene_dir = /tmp/pip-r1dvzseq-build/build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/genes
motif_databases = /tmp/pip-r1dvzseq-build/build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/motif_databases
seqlogo = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/seqlogo
tools = /tmp/pip-r1dvzseq-build/build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools

[params]
fraction = 0.2
use_strand = False
abs_max = 1000
analysis = medium
enrichment = 1.5
width = 200
lwidth = 500
genome = hg19
background = gc,random
cluster_threshold = 0.95
available_tools = MDmodule,MEME,MEMEW,Weeder,GADEM,MotifSampler,trawler,Improbizer,BioProspector,Posmo,ChIPMunk,JASPAR,AMD,HMS,Homer,XXmotif
tools = MDmodule,MEME,MEMEW,Weeder,MotifSampler,trawler,Improbizer,BioProspector,Posmo,ChIPMunk,JASPAR,AMD,HMS,Homer,XXmotif
pvalue = 0.001
max_time = 
ncpus = 2
motif_db = gimme.vertebrate.v3.1.pwm
scan_cutoff = 0.9
use_cache = False
markov_model = 1

[MDmodule]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/MDmodule
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools

[MEME]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/meme.bin
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools

[MEMEW]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/meme.bin
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools

[Weeder]
bin = /home/carlos/anaconda2/envs/gimme/bin/weeder2
dir = /home/carlos/anaconda2/envs/gimme/bin/weeder2

[GADEM]
bin = /home/carlos/anaconda2/envs/gimme/bin/gadem
dir = /home/carlos/anaconda2/envs/gimme/bin

[MotifSampler]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/MotifSampler
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools

[trawler]
bin = /home/carlos/anaconda2/envs/gimme/bin/trawler
dir = /home/carlos/anaconda2/envs/gimme/bin

[Improbizer]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/ameme
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools

[BioProspector]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/BioProspector
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools

[Posmo]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/posmo
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools

[ChIPMunk]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/ChIPMunk/ChIPMunk.sh
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/ChIPMunk

[JASPAR]
bin = /bin/false
dir = /tmp/pip-r1dvzseq-build

[AMD]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/AMD.bin
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools

[HMS]
bin = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/HMS/hms
dir = build/bdist.linux-x86_64/wheel/gimmemotifs-0.11.1.data/data/gimmemotifs/tools/HMS

[Homer]
bin = /home/carlos/anaconda2/envs/gimme/bin/homer2
dir = /home/carlos/anaconda2/envs/gimme/bin

[XXmotif]
bin = /home/carlos/anaconda2/envs/gimme/bin/XXmotif
dir = /home/carlos/anaconda2/envs/gimme/bin
```

**Comment by simonvh** [comment]
Can you try the following:

```
$ source activate gimme
$ pip uninstall gimmemotifs
$ pip install git+https://github.com/simonvh/gimmemotifs@0.11.1
```

And see if that works?

**Comment by c-guzman** [comment]
Yep that seems to have solved it!

**Comment by simonvh** [comment]
Glad it did. I am confused though. Apparently pip behaves differently on a tarball as compared to a git pull. Very strange.
