### ISSUE TITLE
struct.error: unpack requires a bytes object of length 8

### ISSUE THREAD

**Issue by crazyhottommy** [simonvh/gimmemotifs#62]
using gimmemotifs:               0.11.1-py36_0 

```
gimme maelstrom gimme_input.txt hg19 maelstrom.out

2018-04-23 22:29:09,302 - INFO - Starting maelstrom
2018-04-23 22:29:09,305 - INFO - Motif scanning (counts)
2018-04-23 22:29:09,305 - INFO - reading table
2018-04-23 22:29:09,401 - INFO - setting threshold
Determining threshold for fpr 0.01 and length 200 based on hg19
Traceback (most recent call last):
  File "/apps/conda/envs/gimme/bin/gimme", line 496, in <module>
    args.func(args)
  File "/apps/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/commands/maelstrom.py", line 29, in maelstrom
    run_maelstrom(infile, genome, outdir, pwmfile, methods=methods)
  File "/apps/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/maelstrom.py", line 193, in run_maelstrom
    pwmfile=pwmfile)
  File "/apps/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/maelstrom.py", line 59, in scan_to_table
    s.set_threshold(fpr=FPR, genome=genome)
  File "/apps/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/scanner.py", line 407, in set_threshold
    fa = RandomGenomicFasta(index, length, 10000)
  File "/apps/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/background.py", line 350, in __init__
    track2fasta(index, tmpbed, tmpfasta, use_strand=True)
  File "/apps/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/genome_index.py", line 628, in track2fasta
    all_seqs = g.get_sequences(chrom, coords)
  File "/apps/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/genome_index.py", line 489, in get_sequences
    seq += self._read(index, fasta, start, end, line_size)
  File "/apps/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/genome_index.py", line 448, in _read
    d_offset = self._get_offset_from_index(index, i_offset)
  File "/apps/conda/envs/gimme/lib/python3.6/site-packages/gimmemotifs/genome_index.py", line 420, in _get_offset_from_index
    d_offset = unpack(self.pack_char, entry)[0]
struct.error: unpack requires a bytes object of length 8

```
what's wrong with it?
Thanks,
Tommy

**Comment by crazyhottommy** [comment]
need to install the genome first. closing now

**Comment by simonvh** [comment]
Thanks for reporting Tommy. Note to self: this could use a clear error message!

(And please report any other issues you might encounter)
